# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11cef1c818353d2c7dc6a0c88456da92512d2b589efae3146c682ecedaa44bf4a1bf29c9112105f2fe413903f6ba08f8919b1dbca3adb9c2f8cc86e2766747ac

test:
  secret_key_base: edfb28dc336e7eca6c78f68947cf71fca7fa44a6f1303eba94c45f23afd45b24260a51c4ff0c5bc38812060346361289dfb8c8691a33061bd22eb61bf68f26fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
